import { z } from 'zod';
import { deriveRng, sec, shuffle } from '@fitil/sim';
import type { CharKit, SuperKind } from '@fitil/sim';

/** Raritățile (Q-006): raritatea aduce abilități mai neobișnuite, nu cifre mai mari. */
export const RARITIES = ['common', 'rare', 'epic', 'legendary', 'mythic'] as const;
export type Rarity = (typeof RARITIES)[number];

export const RARITY: Record<Rarity, { name: string; color: string; price: number }> = {
  common: { name: 'Common', color: '#9aa3c0', price: 0 },
  rare: { name: 'Rare', color: '#4f9dff', price: 250 },
  epic: { name: 'Epic', color: '#b169ff', price: 600 },
  legendary: { name: 'Legendary', color: '#ffc21a', price: 1200 },
  mythic: { name: 'Mythic', color: '#ff4d6d', price: 2500 },
};

/** Vocile sintetizate ale personajelor (și ale pachetelor de voce din magazin). */
export const VOICE_IDS = [
  'hihi',
  'hoho',
  'yeehaw',
  'whistle',
  'vai',
  'muahaha',
  'robot',
  'whoosh',
  'sizzle',
  'boo',
  'tada',
  'cat',
  'pirate',
  'opera',
] as const;
export type VoiceId = (typeof VOICE_IDS)[number];

export const WALKS = [
  'hop',
  'stomp',
  'dash',
  'twirl',
  'waddle',
  'glide',
  'robot',
  'dribble',
  'float',
] as const;
export type Walk = (typeof WALKS)[number];

const SUPERS = [
  'bigbomb',
  'dash',
  'sticky',
  'cluster',
  'purse',
  'timestop',
  'warp',
  'quake',
  'penalty',
  'boo',
  'swap',
] as const satisfies readonly SuperKind[];

const KitSchema = z.object({
  speed: z.number().int().min(100).max(315),
  range: z.number().int().min(1).max(3),
  bombs: z.number().int().min(1).max(3),
  maxBombs: z.number().int().min(3).max(8),
  lives: z.number().int().min(1).max(2),
  kick: z.boolean().optional(),
  glove: z.boolean().optional(),
  noGlove: z.boolean().optional(),
  noShield: z.boolean().optional(),
  shield: z.number().int().positive().optional(),
  shieldPct: z.number().int().min(10).max(100).optional(),
  magnet: z.boolean().optional(),
  immune: z.boolean().optional(),
  bigFirst: z.boolean().optional(),
  timers: z.boolean().optional(),
  ricochet: z.boolean().optional(),
  oil: z.boolean().optional(),
  fuseAdd: z.number().int().min(0).max(20).optional(),
  ghost: z.boolean().optional(),
  pigeon: z.boolean().optional(),
}) satisfies z.ZodType<CharKit>;

const CharSchema = z.object({
  id: z.string().regex(/^[a-z]+$/),
  name: z.string().min(1),
  rarity: z.enum(RARITIES),
  tagline: z.string().min(1),
  kit: KitSchema,
  /** Semnătura, pe scurt (cartea personajului, HUD). */
  signature: z.string().min(1),
  pros: z.array(z.string().min(1)).min(1),
  cons: z.array(z.string().min(1)).min(1),
  /** Ultimate-ul (în simulare: `SuperKind`): numele și descrierea din joc, tipul și viteza de încărcare. */
  ultimate: z.object({
    name: z.string().min(1),
    desc: z.string().min(1),
    kind: z.enum(SUPERS),
    /** Viteza de încărcare, în procente (Ultimate-urile puternice se încarcă mai greu). */
    pct: z.number().int().min(70).max(150),
  }),
  /** Culoarea de bază (offline, în FFA) și culoarea exclusivă de la nivelul 5. */
  color: z.string().regex(/^#[0-9a-f]{6}$/i),
  signatureColor: z.string().regex(/^#[0-9a-f]{6}$/i),
  /** Mărimea corpului la randare (1 = normal). */
  size: z.number().min(0.8).max(1.2),
  walk: z.enum(WALKS),
  voice: z.enum(VOICE_IDS),
  /** Replici: la lovitură/moarte, la victorie, la eliminare. */
  quips: z.array(z.string().min(1)).min(2),
  win: z.array(z.string().min(1)).min(1),
  kill: z.array(z.string().min(1)).min(1),
});
export type Character = z.infer<typeof CharSchema>;

/** Rosterul (nume de lucru, originale). Viteza e în unități pe tick: 3.3 pătrățele/s = 165. */
export const CHARACTERS: Character[] = z.array(CharSchema).parse([
  {
    id: 'bubu',
    name: 'Bubu',
    rarity: 'common',
    tagline: 'Round, cheerful, starts with a bang.',
    kit: { speed: 165, range: 1, bombs: 1, maxBombs: 8, lives: 1, bigFirst: true },
    signature: 'First bomb of every round is huge (+2 range).',
    pros: ['Huge first bomb', 'No weak spots'],
    cons: ['Nothing special after the first bomb'],
    ultimate: {
      name: 'Big Bang',
      desc: 'Drops a giant bomb (+2 range) on top of your normal ones.',
      kind: 'bigbomb',
      pct: 100,
    },
    color: '#5ad15a',
    signatureColor: '#b7ff5a',
    size: 1,
    walk: 'hop',
    voice: 'hihi',
    quips: ['Hee hee… ouch!', 'Oopsie!', 'Not fair!'],
    win: ['Hee hee hee, I won!', 'Hee hee, too easy!'],
    kill: ['Hee hee!', 'Boop!'],
  },
  {
    id: 'gugu',
    name: 'Gugu',
    rarity: 'common',
    tagline: 'Heavy, stubborn, hard to get rid of.',
    kit: { speed: 138, range: 2, bombs: 1, maxBombs: 8, lives: 2 },
    signature: 'Two lives: survives the first hit.',
    pros: ['2 lives', 'Starts with range 2'],
    cons: ['Slowest walker', 'Big body'],
    ultimate: {
      name: 'Earthquake',
      desc: 'Shoves every bomb within 2 tiles away from him.',
      kind: 'quake',
      pct: 100,
    },
    color: '#b08a5a',
    signatureColor: '#7a4a1c',
    size: 1.15,
    walk: 'stomp',
    voice: 'hoho',
    quips: ['Ho ho… ouch!', 'Hmpf!', 'I’ll get up…'],
    win: ['Ho ho ho!', 'Ho ho, who’s the boss?'],
    kill: ['Ho!', 'Down you go.'],
  },
  {
    id: 'zuzu',
    name: 'Zuzu',
    rarity: 'common',
    tagline: 'Blink and you missed her.',
    kit: { speed: 200, range: 1, bombs: 1, maxBombs: 5, lives: 1 },
    signature: 'Fastest character in the game.',
    pros: ['Top speed from the start', 'Small body'],
    cons: ['At most 5 bombs'],
    ultimate: {
      name: 'Dash',
      desc: 'Dashes up to 3 tiles in the direction she faces.',
      kind: 'dash',
      pct: 100,
    },
    color: '#e0a35a',
    signatureColor: '#ff3b2f',
    size: 0.88,
    walk: 'dash',
    voice: 'yeehaw',
    quips: ['Too fast!', 'Eeek!', 'I slipped!'],
    win: ['Yee-haw!', 'You didn’t even see me!'],
    kill: ['Zoom!', 'Yee-haw!'],
  },
  {
    id: 'striker',
    name: 'Striker',
    rarity: 'rare',
    tagline: 'Every bomb is a ball.',
    kit: { speed: 168, range: 1, bombs: 1, maxBombs: 8, lives: 1, kick: true, ricochet: true, noGlove: true },
    signature: 'Permanent Kick; kicked bombs bounce back once.',
    pros: ['Kick forever (others get 3 kicks)', 'Kicked bombs ricochet once'],
    cons: ['Can’t pick up the Glove'],
    ultimate: {
      name: 'Penalty',
      desc: 'Kicks every bomb in his line of sight, all at once.',
      kind: 'penalty',
      pct: 100,
    },
    color: '#2fb4ff',
    signatureColor: '#ffffff',
    size: 0.95,
    walk: 'dribble',
    voice: 'whoosh',
    quips: ['Foul!', 'Offside!', 'Red card?!'],
    win: ['GOOOAL!', 'Champions!'],
    kill: ['Goal!', 'Top corner!'],
  },
  {
    id: 'fifi',
    name: 'Fifi',
    rarity: 'epic',
    tagline: 'Graceful, and grabs everything.',
    kit: { speed: 172, range: 1, bombs: 1, maxBombs: 8, lives: 1, magnet: true },
    signature: 'Magnet: picks up good power-ups from neighbouring tiles.',
    pros: ['Collects power-ups one tile away', 'Quick'],
    cons: ['Small range at the start'],
    ultimate: {
      name: 'Cluster',
      desc: 'Four mini-bombs in a cross, two tiles away.',
      kind: 'cluster',
      pct: 115,
    },
    color: '#ff9ad0',
    signatureColor: '#ff3fa0',
    size: 0.95,
    walk: 'twirl',
    voice: 'whistle',
    quips: ['My dress!', 'Not like that!', 'Ugh!'],
    win: ['Whee-hoo!', 'With grace!'],
    kill: ['Tee-hee!', 'Pardon me!'],
  },
  {
    id: 'veta',
    name: 'Auntie Veta',
    rarity: 'epic',
    tagline: 'Handbag, headscarf, zero patience.',
    kit: { speed: 148, range: 1, bombs: 1, maxBombs: 8, lives: 1, glove: true, shield: sec(8) },
    signature: 'Permanent Glove and an 8-second shield at the start.',
    pros: ['Glove forever (others get 3 throws)', '8s shield at the start'],
    cons: ['Slow'],
    ultimate: {
      name: 'The Handbag',
      desc: 'Swings a bomb 4 to 9 tiles away, over walls.',
      kind: 'purse',
      pct: 80,
    },
    color: '#ffb870',
    signatureColor: '#d8306a',
    size: 1.05,
    walk: 'waddle',
    voice: 'vai',
    quips: ['Oh my goodness!', 'You rascals!', 'My hair!'],
    win: ['Shame on all of you!', 'That’s manners!'],
    kill: ['Serves you right!', 'Tsk tsk!'],
  },
  {
    id: 'chef',
    name: 'Chef',
    rarity: 'epic',
    tagline: 'Cooks with fire. Literally.',
    kit: { speed: 158, range: 1, bombs: 1, maxBombs: 8, lives: 1, oil: true, fuseAdd: 6 },
    signature: 'His blasts leave oil for 2s that slows everyone else.',
    pros: ['Oil slows opponents by 40%', 'Great for trapping'],
    cons: ['His fuses are 0.3s longer'],
    ultimate: {
      name: 'Sticky Sauce',
      desc: 'Kicks a sticky bomb that glues itself to the first player it hits.',
      kind: 'sticky',
      pct: 90,
    },
    color: '#f4f4f8',
    signatureColor: '#ff7a1a',
    size: 1.05,
    walk: 'waddle',
    voice: 'sizzle',
    quips: ['Burnt!', 'Too much salt!', 'Mamma mia!'],
    win: ['Bon appétit!', 'Chef’s kiss!'],
    kill: ['Well done!', 'Order up!'],
  },
  {
    id: 'maestru',
    name: 'Master Fitil',
    rarity: 'legendary',
    tagline: 'Knows every fuse by heart.',
    kit: { speed: 160, range: 2, bombs: 1, maxBombs: 6, lives: 1, timers: true },
    signature: 'Sees the countdown of every bomb.',
    pros: ['Bomb timers on screen', 'Starts with range 2'],
    cons: ['At most 6 bombs'],
    ultimate: {
      name: 'Time Stop',
      desc: 'For 1.5s everyone else’s bombs freeze. His keep ticking.',
      kind: 'timestop',
      pct: 130,
    },
    color: '#9ad7ff',
    signatureColor: '#ffd23f',
    size: 1,
    walk: 'glide',
    voice: 'muahaha',
    quips: ['Impossible!', 'My calculations…', 'Nooo!'],
    win: ['Mwa-ha-ha!', 'All according to plan!'],
    kill: ['Predictable.', 'Mwa-ha!'],
  },
  {
    id: 'robo',
    name: 'Robo-Mici',
    rarity: 'legendary',
    tagline: 'Beep. Boop. Boom.',
    kit: { speed: 160, range: 1, bombs: 1, maxBombs: 8, lives: 1, kick: true, immune: true, noShield: true },
    signature: 'Immune to slow, reverse, dizzy and hiccups; permanent Kick.',
    pros: ['Immune to bad power-ups', 'Kick forever'],
    cons: ['Can’t pick up the Shield'],
    ultimate: {
      name: 'Portal Jump',
      desc: 'Teleports to the farther portal, or to a safe spot far away.',
      kind: 'warp',
      pct: 100,
    },
    color: '#c8ccd8',
    signatureColor: '#ff3b3b',
    size: 1,
    walk: 'robot',
    voice: 'robot',
    quips: ['Fatal error!', 'Beep… boop…', 'Rebooting…'],
    win: ['Beep-boop! Victory!', 'Mission complete!'],
    kill: ['Target down.', 'Beep!'],
  },
  {
    id: 'ghost',
    name: 'Ghost',
    rarity: 'mythic',
    tagline: 'Crates? What crates?',
    kit: { speed: 170, range: 1, bombs: 1, maxBombs: 8, lives: 1, ghost: true, noShield: true },
    signature: 'Walks through one crate every 20 seconds.',
    pros: ['Phases through crates', 'Quick'],
    cons: ['Can’t pick up the Shield', 'Blasts still hit him inside a crate'],
    ultimate: { name: 'Boo!', desc: 'Invisible to opponents for 2 seconds.', kind: 'boo', pct: 110 },
    color: '#e8f0ff',
    signatureColor: '#7dffd8',
    size: 0.95,
    walk: 'float',
    voice: 'boo',
    quips: ['Boo… hoo!', 'I’m see-through!', 'Not again!'],
    win: ['Boo-yah!', 'Spooky win!'],
    kill: ['Boo!', 'Gotcha!'],
  },
  {
    id: 'magician',
    name: 'Magician',
    rarity: 'mythic',
    tagline: 'Now you see the bomb… now it’s a pigeon.',
    kit: { speed: 160, range: 1, bombs: 1, maxBombs: 6, lives: 1, pigeon: true, shieldPct: 50 },
    signature: 'Once per round, an enemy bomb that would hit him turns into a pigeon.',
    pros: ['Survives one enemy blast per round'],
    cons: ['At most 6 bombs', 'Shields last half as long'],
    ultimate: { name: 'Switcheroo', desc: 'Swaps places with the nearest opponent.', kind: 'swap', pct: 90 },
    color: '#8a5cff',
    signatureColor: '#ffd23f',
    size: 1,
    walk: 'glide',
    voice: 'tada',
    quips: ['That wasn’t the trick!', 'Abracada… ouch!', 'Where’s my hat?'],
    win: ['Ta-daaa!', 'And for my next trick…'],
    kill: ['Poof!', 'Ta-da!'],
  },
]);

export const CHAR_IDS = CHARACTERS.map((c) => c.id);
export const charById = (id: string | null | undefined): Character =>
  CHARACTERS.find((c) => c.id === id) ?? CHARACTERS[0]!;
export const charPrice = (c: Character): number => RARITY[c.rarity].price;
/** Personajele gratuite de la început. */
export const FREE_CHARS = CHARACTERS.filter((c) => c.rarity === 'common').map((c) => c.id);

/**
 * Personajele boților: amestecate din seed (identic pe server și client), altele decât cele
 * ale oamenilor cât se poate.
 */
export function botChars(seed: number, taken: readonly (string | null)[], n: number): string[] {
  const free = CHAR_IDS.filter((c) => !taken.includes(c));
  const pool = shuffle(deriveRng(seed, 0xc4a5), free.length ? free : [...CHAR_IDS]);
  return Array.from({ length: n }, (_, i) => pool[i % pool.length]!);
}
